USE NB;

CREATE TABLE 게시글(
	고유번호 INT,
	제목 VARCHAR(30),
	작성자 VARCHAR(10),
	작성일자 DATE,
	내용 VARCHAR(1000),
	PRIMARY KEY(고유번호)
);

CREATE TABLE 댓글(
	댓글번호 INT,
	게시글번호 INT,
	작성자 VARCHAR(10),
	작성시간 DATETIME,
	내용 VARCHAR(300),
	PRIMARY KEY(댓글번호, 게시글번호),
	FOREIGN KEY(게시글번호) REFERENCES 게시글(고유번호)
);

CREATE SEQUENCE 게시글번호
START WITH 1
INCREMENT BY 1
MAXVALUE 99999;

CREATE SEQUENCE 댓글번호
START WITH 1
INCREMENT BY 1
MAXVALUE 999999;

ALTER SEQUENCE 게시글번호 restart;

INSERT INTO 게시글 VALUES (NEXTVAL(게시글번호), "안녕하세요.", "홍길동", '2023-06-03', "123456789");
INSERT INTO 게시글 VALUES (NEXTVAL(게시글번호), "나는 길동이에요.", "홍길동", '2023-06-03', "123456789");

SELECT * FROM 게시글 articles LIMIT 0,5;

DELETE FROM 게시글;